import { defineConfig } from "vite";

// Minimal Vite config for the throwaway spike. `public/sheet.jpg` (generated by
// `npm run gen`) is served at `/sheet.jpg`.
export default defineConfig({
  server: { open: true },
});
